runtime: go
api_version: go1

skip_files:
- ^node_modules$

handlers:
- url: /$
  static_files: ../static/index.html
  upload: ../static/index.html

- url: /(.*)/$
  static_files: ../static/\1/index.html
  upload: ../static/.*/index.html

- url: /css
  static_dir: ../static/css

- url: /js
  static_dir: ../static/js

- url: /img
  static_dir: ../static/img

- url: /.*
  script: _go_app
